# Site info
site_name: Genesis Writes
site_url: https://genwrites.com/ #custom, primary domain

# Theme with Material for MkDocs
theme:
  name: material
  custom_dir: docs
  language: en

  # Header and browser tab logo
  logo: assets/logo.png
  favicon: assets/img/favicon.ico

  palette:
    # Palette toggle for light mode
    - scheme: default
      primary: custom
      accent: custom
      toggle:
        icon: material/weather-night
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      primary: custom
      accent: custom
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
  
  features:

    - content.action.view

    # Enable copying code
    - content.code.copy

    # Back to top anchor
    - navigation.top

    # Include links to previous and next page of current page
    - navigation.footer

    # URL in address bar is automatically updated with active anchor highlighted in toc
    - navigation.tracking

    # Top-level sections rendered in a menu layer below header
    - navigation.tabs

    # Lock nav tabs when user scrolls down a page
    - navigation.tabs.sticky

    # Top-level sections rendered as groups in sidebar
    - navigation.sections

    # Ensure toc always rendered on the left, within the nav sections
    #- toc.integrate
    
    # Display the likeliest completion in search bar
    - search.suggest

    # Highlight search query matches in the result
    - search.highlight
  
  icon:
    # For social cards
    logo: assets/img/favicon.ico

    # Icons for tags    
    tag:
      knowledge-base: fontawesome/solid/brain
      sop: fontawesome/solid/users-gear
      training: fontawesome/solid/lightbulb
      fun: fontawesome/solid/face-smile
      blog: fontawesome/brands/microblog
  
# Power up our docs!
plugins:
  # Present images in a lightbox on click
  - glightbox

  # Enable docs search
  - search

  # Add a last updated date
  - git-revision-date-localized

  # Add a blog
  - blog:
      # Format Day, Month DD, YYYY
      post_date_format: full
      # Display reading time of a post
      post_readtime: true
      # Display post titles in a table of contents
      blog_toc: true
      # Display "Continue reading" after <!-- more --> separator in post
      post_excerpt: optional
      # Displays 5 posts per page on blog index
      pagination_per_page: 5
  - tags:
      # Tag index, makes each tag clickable
      tags_file: tags.md
  
  # Social cards
  - social

# Additional site info
    
extra:
  # Rendered next to the copyright notice as part of the footer
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/genesis-writing
      name: genesis-writing on GitHub
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/genesis-sorto/
      name: Genesis Sorto on LinkedIn
  
  # Retain "Made with Material for MkDocs" in footer
  generator: true

  # Associate each tag with a unique identifier
  tags:
    Knowledge Base: knowledge-base
    SOP: sop
    Training: training
    Fun: fun
    Blog: blog
    Programming: programming

  # Google Analytics
  analytics:
    provider: google
    property: !ENV GOOGLE_ANALYTICS_KEY

  # Cookie consent for Google Analytics
  consent:
    title: Google Analytics Consent
    description: >- 
      I use cookies to recognize your visits and preferences, and to track how
      my portfolio performs over time. If you leave Google Analytics checked
      and click 'Accept,' you’ll help me understand how visitors interact with
      my work. To opt out, simply uncheck the circle before clicking 'Accept'.
    actions:
      - accept

# For Footer, include option for visitors to update cookie consent form
copyright: >
  Copyright &copy; 2024 Genesis Sorto - Technical Writer -
  <a href="#__consent">Change cookie settings</a>

# Customize theme even further
extra_css:
  - stylesheets/extra.css

# Markdown extensions
markdown_extensions:

  # Use icons and emojis
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg


  # For callouts
  - admonition

  # Render keyboard keys and combos (doesn't work in lists?)
  - pymdownx.keys

  # Emphasize text using special characters, i.e. for **bold** and _italic_ formatting
  - pymdownx.betterem

  # For mark characters
  - pymdownx.mark

  # Makes admonitions collapsible
  - pymdownx.details

  # Allows nesting admonitions, tabs, lists and all other elements
  - pymdownx.superfences:
      custom_fences:
            # Allows mermaid.js diagrams
            - name: mermaid
              class: mermaid
              format: !!python/name:pymdownx.superfences.fence_code_format

  #  enables syntax highlighting on code blocks and inline code blocks,
  # and allows to include source code directly from other files
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets

  # Internal anchor links for headings
  - toc:
      permalink: 🔗

# Top nav bar elements
nav:
  # Home page
  - Home: index.md

  # Knowledge base portfolio pieces - Kap user guide
  - Knowledge Base:
    - Project Info: knowledge-base/introduction_knowledge_base.md
    - Setting Up Kap:
      - knowledge-base/setting_up_kap/Installation-Guide_327695.md
      - Screen Recording Access Guide: knowledge-base/setting_up_kap/Screen-Recording-Permission-Guide_393254.md
    - Quick Start:
      - knowledge-base/Quick-Start-Guide_327712.md
    - Comprehensive User Guide:
      - knowledge-base/comprehensive_user_guide/Tool-Bar_393330.md
      - Preferences and Plugins: knowledge-base/comprehensive_user_guide/Preferences-and-Plugins_360709.md
      - Editor: knowledge-base/comprehensive_user_guide/Editor_262804.md
      - How to Complete a Recording: knowledge-base/comprehensive_user_guide/How-to-Complete-a-Recording_360882.md

  # Standard operation procedure portfolio pieces
  - SOP:
    - SOP Intro: sop/SOP-intro.md
    - Business Operation Process: sop/business-operation-process.md
  
  # Training portfolio pieces
  - Training:
    - Training Docs Intro: training-docs/training-docs-intro.md
    - Training Plan: training-docs/training-plan.md
    - Employee Training Evaluation Profile: training-docs/employee-training-evaluation-profile.md
  
  # Fun portfolio pieces
  - Fun:
    - Fun Intro: fun/fun-intro.md
    - How to Cook Shrimp Fried Rice: fun/how-to-cook-shrimp-fried-rice.md
    - Gameboy Colour Technical Data Sheet: fun/gameboy-colour-technical-data-sheet-portfolio.md

  # Crowrite CS50 Final Project
  - Crowrite: crowrite.md

  # Blog posts
  - Blog:
    - blog/index.md

